# This is a basic workflow to help you get started with Actions

name: Test Job

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
 
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
        matrix:
            node-version: [16.x]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version}}
        uses: actions/setup-node@v3.1.1
        with:
              node-version: ${{ matrix.node-version}}
      - name: Unit Testing
        run: |
            npm ci
            npm run build
            npm run test
            npm init // fill the required things CLI asked
            npm i express
            npm i mocha supertest 
        env:
            CI: false
                        
  After_test_job: 
    runs-on: ubuntu-latest
    name: Starts after JOB1 is complete
    needs: [build]
            
    steps:
            - uses: wxdlong/hello-action@v7
              with:
                who-to-greet: 'Test was complete' 
